name: Producción Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag RC aprobado para producción"
        required: true

  repository_dispatch:
    types: [trigger-prod]


jobs:
  prod-release:
    runs-on: ubuntu-latest   # 🔹 Ubuntu runner de GitHub
    environment:
      name: prod
      url: https://miapp.prod.example.com

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Descargar artefacto de release
        run: |
          echo "Desplegando versión: ${{ github.event.inputs.tag_name }}"

      - name: Verificar Docker instalado
        run: |
          docker --version
          docker compose version || true

